server:
  port: 8000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: spring-6-rest-mvc
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/*
        - id: spring-6-r2dbc
          uri: http://localhost:8002
          predicates:
            - Path=/api/v2/*
        - id: spring-6-webfluxfn
          uri: http://localhost:8003
          predicates:
            - Path=/api/v3/*

# Debugging: #
#      httpServer:
#        wiretap: true
#      httpClient:
#        wiretap: true
#
#logging:
#  level:
#    root: error
#    reactor.netty: trace
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: trace